services:
  dev: &dev
    platform: linux/amd64
    build:
      context: ../..
      dockerfile: Dockerfile
      target: package-ci
    extra_hosts:
      - host.docker.internal:host-gateway
    working_dir: /code
    volumes:
      - ./:/code
    environment:
      - TEST_PREFIX
      - ABS_ACCOUNT_NAME
      - ABS_ACCOUNT_KEY
      - ABS_CONTAINER_NAME
      - SNOWFLAKE_HOST
      - SNOWFLAKE_PORT
      - SNOWFLAKE_USER
      - SNOWFLAKE_PASSWORD
      - SNOWFLAKE_PRIVATE_KEY
      - SNOWFLAKE_DATABASE
      - SNOWFLAKE_WAREHOUSE
      - BQ_KEY_FILE

  # Alias for standalone repo workflow compatibility
  production:
    <<: *dev

  ci:
    platform: linux/amd64
    image: ci-table-backend-utils
    build:
      context: ../..
      dockerfile: Dockerfile
      target: package-ci
    working_dir: /code
    volumes:
      - .:/code
    environment:
      - TEST_PREFIX
      - SNOWFLAKE_HOST
      - SNOWFLAKE_PORT
      - SNOWFLAKE_USER
      - SNOWFLAKE_PASSWORD
      - SNOWFLAKE_PRIVATE_KEY
      - SNOWFLAKE_DATABASE
      - SNOWFLAKE_WAREHOUSE
      - BQ_KEY_FILE

  dev-xdebug:
    <<: *dev
    build:
      context: ../..
      dockerfile: Dockerfile
      target: package-ci-xdebug
